# Generated by Skyramp v1.3.25 on 2026-06-03 20:19:08.553461174 +0000 UTC m=+491.519779755
# Command: skyramp generate contract rest http://localhost:8000/api/v1/orders/{order_id} \
# 		--api-schema http://localhost:8000/openapi.json \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output orders_get_contract_test.py \
# 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/backend/tests/python \
# 		--overwrite \
# 		--parent-request-data order_id={"customer_email": "contractget@example.com", "items": [{"product_id": 1, "quantity": 1}]} \
# 		--parent-status-code order_id=201 \
# 		--provider \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
import pytest


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")
order_id = "order_id"

def get_header():
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")
    return headers


@pytest.fixture(autouse=True)
def before_all():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = get_header()

    # Request Body
    orders_POST_request_body = r'''{
        "customer_email": "contractget@example.com",
        "items": [
            {
                "product_id": 1,
                "quantity": 1
            }
        ]
    }'''

    # Execute Request
    orders_POST_response = client.send_request(
        url=URL,
        path="/api/v1/orders",
        method="POST",
        body=orders_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert orders_POST_response.status_code == 201

    # Update global path param values
    global order_id
    order_id = skyramp.get_response_value(orders_POST_response, "order_id")


@pytest.fixture(autouse=True)
def after_all(before_all):
    yield

    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = get_header()

    # Execute Request
    orders_order_id_DELETE_response = client.send_request(
        url=URL,
        path="/api/v1/orders/{order_id}",
        method="DELETE",
        headers=headers,
        path_params={"order_id": order_id}
    )

    # Generated Assertions
    assert orders_order_id_DELETE_response.status_code == 200


# contract test for /api/v1/orders/{order_id} GET
def test_v_1_orders_order_id_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = get_header()

    # Expected Response Body
    expected_v1_orders_order_id_GET_response_body = r'''{
        "created_at": "2022-01-01T00:00:00",
        "customer_email": "abc@mail.com",
        "discount_percent": 0,
        "items": [
            {
                "order_item_id": 1,
                "product_id": 1,
                "quantity": 2
            }
        ],
        "order_id": 1,
        "status": "pending",
        "total_amount": 19.98,
        "updated_at": "2022-01-01T00:00:00"
    }'''

    # Execute Request
    v1_orders_order_id_GET_response = client.send_request(
        url=URL,
        path="/api/v1/orders/{order_id}",
        method="GET",
        headers=headers,
        path_params={"order_id": order_id}
    )

    # Generated Assertions
    assert v1_orders_order_id_GET_response.status_code == 200
    assert skyramp.get_response_value(v1_orders_order_id_GET_response, "discount_percent") >= 0
    assert skyramp.get_response_value(v1_orders_order_id_GET_response, "total_amount") >= 0
    assert skyramp.get_response_value(v1_orders_order_id_GET_response, "order_id") > 0
    assert skyramp.get_response_value(v1_orders_order_id_GET_response, "items.0") is not None
    assert skyramp.get_response_value(v1_orders_order_id_GET_response, "items.0.quantity") > 0
    assert skyramp.check_schema(v1_orders_order_id_GET_response, expected_v1_orders_order_id_GET_response_body)
    assert skyramp.get_response_value(v1_orders_order_id_GET_response, "created_at") is not None
    assert skyramp.get_response_value(v1_orders_order_id_GET_response, "customer_email") is not None
    assert skyramp.get_response_value(v1_orders_order_id_GET_response, "discount_percent") is not None


if __name__ == "__main__":
    before_all()
    test_v_1_orders_order_id_get()
    after_all()
