// Generated by Skyramp v1.3.25 on 2026-06-03 20:19:00.141575267 +0000 UTC m=+483.107893838
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output edit_order_form.spec.ts \
// 		--output-dir /home/runner/work/demoshop-testbot/demoshop-testbot/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/demoshop-testbot/demoshop-testbot/.skyramp/edit_order_form_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(617000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    await page.waitForTimeout(3000);
    await page.goto("http://localhost:5173/orders");
    await page.waitForTimeout(2000);
    await page.goto("http://localhost:5173/orders/1");
    await page.waitForSelector("text=Edit Order");
    await page.getByTestId("order-detail-edit-btn").click();
    await page.getByTestId("edit-order-input-discount").fill("10");
    await expect(page.getByTestId("edit-order-input-discount")).toHaveValue("10");
    await page.getByTestId("edit-order-submit-btn").click();
    await expect(page.getByTestId("edit-order-heading")).toContainText("Edit order");
    await expect(page.getByTestId("edit-order-error")).toContainText("Failed to update order");
    await expect(errors).toHaveLength(0);
});
